"""create_initial_models

Revision ID: 6040860e7e48
Revises: 
Create Date: 2026-09-26 18:00:00.476798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6040860e7e48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('trackers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='tracker_status', native_enum=False), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackers_mqtt_topic'), 'trackers', ['mqtt_topic'], unique=False)
    op.create_index(op.f('ix_trackers_organization_id'), 'trackers', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'USER', name='user_role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tracker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ACTIVE', 'COMPLETED', name='shipment_status', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minimum_temperature', sa.Float(), nullable=False),
    sa.Column('maximum_temperature', sa.Float(), nullable=False),
    sa.Column('grace_readings', sa.Integer(), nullable=False),
    sa.Column('breach_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_organization_id'), 'shipments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracker_id'), 'shipments', ['tracker_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tracker_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TEMPERATURE_BREACH', 'DOOR_OPEN', 'LOW_BATTERY', name='alert_type', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_org_triggered', 'alerts', ['organization_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_shipment_id'), 'alerts', ['shipment_id'], unique=False)
    op.create_index('ix_alerts_shipment_triggered', 'alerts', ['shipment_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_tracker_id'), 'alerts', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tracker_id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('battery', sa.Float(), nullable=False),
    sa.Column('door_status', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_org_timestamp', 'telemetry', ['organization_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_organization_id'), 'telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_telemetry_shipment_id'), 'telemetry', ['shipment_id'], unique=False)
    op.create_index('ix_telemetry_shipment_timestamp', 'telemetry', ['shipment_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_tracker_id'), 'telemetry', ['tracker_id'], unique=False)
    op.create_index('ix_telemetry_tracker_timestamp', 'telemetry', ['tracker_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_tracker_timestamp', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_tracker_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index('ix_telemetry_shipment_timestamp', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_shipment_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_organization_id'), table_name='telemetry')
    op.drop_index('ix_telemetry_org_timestamp', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tracker_id'), table_name='alerts')
    op.drop_index('ix_alerts_shipment_triggered', table_name='alerts')
    op.drop_index(op.f('ix_alerts_shipment_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_index('ix_alerts_org_triggered', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_shipments_tracker_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_organization_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trackers_organization_id'), table_name='trackers')
    op.drop_index(op.f('ix_trackers_mqtt_topic'), table_name='trackers')
    op.drop_table('trackers')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
