"""model_9_compliance_and_history

Revision ID: f93608224598
Revises: 7c5c02e406e5
Create Date: 2026-09-27 17:15:15.147203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93608224598'
down_revision: Union[str, Sequence[str], None] = '7c5c02e406e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('consecutive_violations', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_telemetry_org_shipment_timestamp', 'telemetry', ['organization_id', 'shipment_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_org_shipment_timestamp', table_name='telemetry')
    op.drop_column('shipments', 'consecutive_violations')
    op.drop_column('alerts', 'temperature')
    # ### end Alembic commands ###
